### ISSUE TITLE
$assert on value that is null

### ISSUE THREAD

**Issue by davit-b** [paritytech/scale-ts#143]
## Code
```ts
const breaking_object = {
  author: "acqq",
  num_comments: null, // this value === number | null
  objectID: "12343",
  points: 34,
  title: null,  // this value === string | null
  url: null, // this value === string | null
}

const $shape = $.object(
  $.field("author", $.str),
  
  $.optionalField("num_comments", $.u32), 
  // optionalField doesn't work for the null input. I tried a literal union here 
  // but it gave me an error `typeof value.num_comments !== "string"` 
  // maybe the literal union only allows string literals? 
  
  $.field("objectID", $.str),
  $.field("points", $.u32),
  
  // literalUnions with null constant does not work for the null inputs above. 
  $.optionalField("title", $.literalUnion([$.str, $.constant(null)])), 
  $.optionalField("url", $.literalUnion([$.str, $.constant(null)])), 
)

$.assert($shape, breaking_object)
```
## Error
```js
typeof value.num_comments !== "number" 
  ​​​​​at ​​​​​​​​AssertState.typeof​​​ ​./node_modules/scale-codec/src/common/assert.ts:25​
  ​​​​​at ​​​​​​​​Codec._assert​​​ ​./node_modules/scale-codec/src/codecs/int.ts:37​
  ​​​​​at ​​​​​​​​Codec._assert​​​ ​./node_modules/scale-codec/src/codecs/option.ts:34​
  ​​​​​at ​​​​​​​​Codec._assert​​​ ​./node_modules/scale-codec/src/codecs/object.ts:40​
  ​​​​​at ​​​​​​​​Codec._assert​​​ ​./node_modules/scale-codec/src/codecs/object.ts:79​
  ​​​​​at ​​​​​​​​Object.assert​​​ ​./node_modules/scale-codec/src/common/codec.ts:140​
  ​​​​​at ​​​​​​​​test​​​ ​src/utility/play.ts:33:3​
  ​​​​​at ​​​​​​​​Object.<anonymous>​​​ ​src/utility/play.ts:36:1

typeof value.title !== "string" 
  ​​​​​at ​​​​​​​​AssertState.typeof​​​ ​./node_modules/scale-codec/src/common/assert.ts:25​
  ​​​​​at ​​​​​​​​Codec._assert​​​ ​./node_modules/scale-codec/src/codecs/union.ts:87​
  ​​​​​at ​​​​​​​​Codec._assert​​​ ​./node_modules/scale-codec/src/codecs/option.ts:34​
  ​​​​​at ​​​​​​​​Codec._assert​​​ ​./node_modules/scale-codec/src/codecs/object.ts:40​
  ​​​​​at ​​​​​​​​Codec._assert​​​ ​./node_modules/scale-codec/src/codecs/object.ts:79​
  ​​​​​at ​​​​​​​​Object.assert​​​ ​./node_modules/scale-codec/src/common/codec.ts:140​
  ​​​​​at ​​​​​​​​test​​​ ​src/utility/play.ts:33:3​
  ​​​​​at ​​​​​​​​Object.<anonymous>​​​ ​src/utility/play.ts:36:1
  
typeof value.url !== "string" 
  ​​​​​at ​​​​​​​​AssertState.typeof​​​ ​./node_modules/scale-codec/src/common/assert.ts:25​
  ​​​​​at ​​​​​​​​Codec._assert​​​ ​./node_modules/scale-codec/src/codecs/union.ts:87​
  ​​​​​at ​​​​​​​​Codec._assert​​​ ​./node_modules/scale-codec/src/codecs/option.ts:34​
  ​​​​​at ​​​​​​​​Codec._assert​​​ ​./node_modules/scale-codec/src/codecs/object.ts:40​
  ​​​​​at ​​​​​​​​Codec._assert​​​ ​./node_modules/scale-codec/src/codecs/object.ts:79​
  ​​​​​at ​​​​​​​​Object.assert​​​ ​./node_modules/scale-codec/src/common/codec.ts:140​
  ​​​​​at ​​​​​​​​test​​​ ​src/utility/play.ts:33:3​
  ​​​​​at ​​​​​​​​Object.<anonymous>​​​ ​src/utility/play.ts:36:1​

```

I'm not sure what I'm doing wrong here. 
The literalUnion does not work for null fields, and the optionalField doesn't work for the null input.

Do I need some new function like zod's Nullable? 

Would appreciate any guidance :)

**Comment by tjjfvi** [comment]
> So I should determined how the breaking object represents None, and decide from there.

Exactly!

> I just tested all 3 cases and the above $nullable works. :) :) Love this lib.

Glad you're enjoying it :)

> Btw, I had to remove the `value` field from the following to get it working.

Ah, yes, you're right. I suppose I should've tested (or at least type-checked) the code before I posted it ;)
